In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.set_printoptions(suppress=True)

In [2]:
dataset = pd.read_csv('Heart Attack.csv', sep=';')

In [3]:
X = dataset.iloc[:, :-1].values   # Semua kolom kecuali 'Outcome'
y = dataset.iloc[:, -1].values    # Hanya kolom 'Outcome'

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
print(X)

[[ 64.     66.    160.    ... 160.      1.8     0.012]
 [ 21.     94.     98.    ... 296.      6.75    1.06 ]
 [ 55.     64.    160.    ... 270.      1.99    0.003]
 ...
 [ 45.     85.    168.    ...  96.      1.24    4.25 ]
 [ 54.     58.    117.    ... 443.      5.8     0.359]
 [ 51.     94.    157.    ... 134.     50.89    1.77 ]]


In [6]:
print(y)

['negative' 'positive' 'negative' ... 'positive' 'positive' 'positive']


In [7]:
#Menghilangkan missing value(NaN)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:6])
X[:, 0:6] = imputer.transform(X[:, 0:6])

In [8]:
print(X)

[[ 64.     66.    160.    ... 160.      1.8     0.012]
 [ 21.     94.     98.    ... 296.      6.75    1.06 ]
 [ 55.     64.    160.    ... 270.      1.99    0.003]
 ...
 [ 45.     85.    168.    ...  96.      1.24    4.25 ]
 [ 54.     58.    117.    ... 443.      5.8     0.359]
 [ 51.     94.    157.    ... 134.     50.89    1.77 ]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 ... 1 1 1]


In [11]:
#membagi dataset ke dalam taining set dan test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [12]:
print(X_train)

[[ 79.     74.    155.    ... 168.      2.84    0.023]
 [ 38.     80.    152.    ... 133.      1.19    0.003]
 [ 70.     94.    122.    ... 229.      3.38    2.32 ]
 ...
 [ 45.    103.    115.    ... 113.      2.74    0.066]
 [ 60.     85.    115.    ... 105.      2.37    0.02 ]
 [ 75.     63.    110.    ...  99.      1.02    0.075]]


In [13]:
print(X_test)

[[ 53.     89.    116.    ...  98.      6.04    0.003]
 [ 75.     80.     90.    ...  86.      4.71    0.062]
 [ 31.    132.    125.    ...  92.      8.69    0.003]
 ...
 [ 36.     55.    101.    ... 115.      2.78    0.016]
 [ 71.     60.    124.    ... 200.      1.18    0.014]
 [ 42.    100.    119.    ... 163.     50.46    0.003]]


In [14]:
print(y_train)

[1 0 1 ... 1 1 1]


In [15]:
print(y_test)

[0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 1
 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 0
 0 1 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 0 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0
 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 1 1
 1 1 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1 0
 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1
 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1
 0 1 1 0 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 0:] = sc.fit_transform(X_train[:, 0:])
X_test[:, 0:] = sc.fit_transform(X_test[:, 0:])

In [17]:
print(X_train)

[[ 1.6724233  -0.08248583  1.10107301 ...  0.27571841 -0.2685793
  -0.28712133]
 [-1.33550476  0.04360335  0.98442767 ... -0.18472048 -0.30311166
  -0.30397825]
 [ 1.01214641  0.33781146 -0.18202569 ...  1.07819762 -0.2572778
   1.64889626]
 ...
 [-0.82195606  0.52694525 -0.45419814 ... -0.44782841 -0.27067217
  -0.25087895]
 [ 0.27850542  0.14867768 -0.45419814 ... -0.55307159 -0.27841579
  -0.28964987]
 [ 1.3789669  -0.31364935 -0.64860704 ... -0.63200397 -0.30666953
  -0.24329333]]


In [18]:
print(X_test)

[[-0.22968782  0.13824735 -0.47650855 ... -0.66945035 -0.19173985
  -0.34208463]
 [ 1.37757345  0.00029031 -1.42044928 ... -0.8403463  -0.22511515
  -0.28393625]
 [-1.83694909  0.79737539 -0.14975983 ... -0.75489832 -0.12524018
  -0.34208463]
 ...
 [-1.47166244 -0.38292367 -1.02108974 ... -0.42734776 -0.27354698
  -0.32927228]
 [ 1.08534413 -0.30628087 -0.18606524 ...  0.7831652  -0.31369772
  -0.33124341]
 [-1.03331845  0.3068615  -0.36759231 ...  0.25623603  0.92294512
  -0.34208463]]


In [19]:
#encoding data kategori (atribut) Matrix X yang terbentuk sebelumnya
#bertipe string, jadi perlu diubah ke numerik (int 
#atau float). karna saya sudah float tidak perlu kode berikut.
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [20]:
#untuk mengubah yes or no menjadi 1 dan 0 
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#y = le.fit_transform(y)